---
language: go
go:
  - 1.12.x

install:
  - curl --silent --location https://goo.gl/g1CpPX | bash -s v1.3.0 # Golang dev tools including pre-compiled Ginkgo and other useful tools

script:
  - GO111MODULE=on go mod download
  - GO111MODULE=on go mod verify
  - make analysis test

before_deploy:
  - make build

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: CTtyVTuwtusOxmF4xtPWHwXOUUQ9m6LsZEjUFFv2IgjSjJ0ScxNFgigr+w2vMjrX7MsWkVY9BuvKLEf2jaZXG08Zs0TNyyIV3tzn6qcQZq3xqRzIlmYievG9qqhN39FACph2t6H/aiojssjPBl9BAiv297mCoGimY+uNF5jWvJl6qKplHpMVdy0T+MN6U3M5kHGjp3BJ+BJL1BzIMIdzL0zuaNzckssC2R2BwCHv/07qyjzmane+Vaxyw0IH/QKR00OCfQMKtMaooTC+EJRXgvHTw5Ag1OmgIBhnShOpVzMUVczPwRkc7yf+gmd+xnYJjCytUv+FnLr6og3SGLQP5yAnZ+l1YD4FY0Hq+AN0B/M9320LSlWZEwwjlUHvI4Sx+7W4upsVo8K9lxrtJJEr5ynkstJl0gFOal0ZWeK6JsaAMF2lBXDCqAB0gFgwaDjIlipv/K078KD1JAxsfTvQDCwBzJaAexoW6HRyKe0iF388A5Fqr2LUAKEWdMA4DywYgPOEimyS+hRXr3xmImn5+bmUZyq2TzopWuEpTobBxKzPRmt+xW5j7i4cizPoI19poyvBysSd6195j5Zyh11vPlxBKVAd5J8RAHkWyuayuMpDvGmeSpQRTRB96z47er32uK1UbxfYM48yIbGY3VP7xvJ+Hh8Jx5g0widL5soLvOU=
  file_glob: true
  file: binaries/*
  on:
    condition: $TRAVIS_GO_VERSION =~ ^1\.12
    tags: true
